# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_U', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='Work_exp',
            new_name='work_exp',
        ),
    ]
