# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_U', '0002_auto_20160418_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='template_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
