# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_U', '0003_auto_20160420_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='make_U.Templates'),
        ),
    ]
