# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_U', '0004_auto_20160420_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='order',
            field=models.SmallIntegerField(default=1),
        ),
    ]
