# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_U', '0005_templates_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='id',
        ),
        migrations.AlterField(
            model_name='templates',
            name='order',
            field=models.SmallIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
