# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20160610_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taste_user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other_Gender')], default=None, max_length=1),
        ),
    ]
